version: '3'
services:

  postgres:
    image: "postgres:14.5"
    restart: "always"
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "socket"

